"""change track table

Revision ID: 229f5ce35a6e
Revises: 
Create Date: 2023-12-12 21:05:43.091640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes



# revision identifiers, used by Alembic.
revision: str = '229f5ce35a6e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('collection_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.drop_column('assets', 'album_id')
    op.add_column('tracks', sa.Column('track_metadata', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'track_metadata')
    op.add_column('assets', sa.Column('album_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('assets', 'collection_id')
    # ### end Alembic commands ###
